apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "gsp-cluster.fullname" . }}-direct-kubernetes-through-egressgateway
  labels:
    app.kubernetes.io/name: {{ include "gsp-cluster.name" . }}-kubernetes
    helm.sh/chart: {{ include "gsp-cluster.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  hosts:
    - kubernetes.default.svc.cluster.local
  gateways:
  - mesh
  - {{ include "gsp-cluster.fullname" . }}-kubernetes
  tls:
  - match:
    - gateways:
      - mesh
      port: 443
      sni_hosts:
        - kubernetes.default.svc.cluster.local
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        port:
          number: 443
  - match:
    - gateways:
      - {{ include "gsp-cluster.fullname" . }}-kubernetes
      port: 443
    route:
    - destination:
        host: kubernetes.default.svc.cluster.local
        port:
          number: 443
      weight: 100
