apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "gsp-cluster.fullname" . }}-kubernetes
  labels:
    app.kubernetes.io/name: {{ include "gsp-cluster.name" . }}-kubernetes
    helm.sh/chart: {{ include "gsp-cluster.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 443
      name: tls
      protocol: TLS
    hosts:
      - kubernetes.default.svc.cluster.local
    tls:
      mode: MUTUAL
      serverCertificate: /etc/certs/cert-chain.pem
      privateKey: /etc/certs/key.pem
      caCertificates: /etc/certs/root-cert.pem
